name: Salesforce Code Analyzer - on pull request

on:
  pull_request:
    branches:
      - main
      - epic/*

run-name: "Code Analyzer of committed files on pull request ${{ github.event.number }}"

jobs:
  run-code-analyzer:
    runs-on: ubuntu-latest
    steps:
      - name: Check out files
        uses: actions/checkout@v4

      - name: Update Node to Version 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Salesforce CLI
        run: npm install -g @salesforce/cli@latest

      - name: Install Salesforce Code Analyzer Plugin
        run: sf plugins install @salesforce/sfdx-scanner@latest

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          separator: '\",\"'

      - name: Run Salesforce Code Analyzer
        id: run-code-analyzer
        uses: forcedotcom/run-code-analyzer@v1
        continue-on-error: true
        with:
          run-command: run
          run-arguments: --normalize-severity --target "\"${{ steps.changed-files.outputs.all_changed_files }}""\"" --outfile results.html
          results-artifact-name: salesforce-code-analyzer-results

      - name: Save Analysis as Comment
        uses: actions/github-script@v7.0.0
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Salesforce Code Analyzer finished with exit-code: ${{steps.run-code-analyzer.outputs.exit-code}} and sev1: ${{steps.run-code-analyzer.outputs.num-sev1-violations}}  sev2: ${{steps.run-code-analyzer.outputs.num-sev2-violations}}  sev3: ${{steps.run-code-analyzer.outputs.num-sev3-violations}}'    
            })

      - name: Check the outputs to determine whether to fail
        if: |
          steps.run-code-analyzer.outputs.exit-code > 0 ||
          steps.run-code-analyzer.outputs.num-sev1-violations > 0 ||
          steps.run-code-analyzer.outputs.num-sev2-violations > 0
        run: exit 1
